/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC165 } from "./ERC165";
export type { Lock } from "./Lock";
export type { MusicShop } from "./MusicShop";
